server:
  port: 8090
  servlet:
    session:
      timeout: 10m
  tomcat:
#    accesslog:
#      directory: /logs
#      enabled: true
#    connection-timeout: 60s
    mbeanregistry:
      enabled: true

spring:
  application:
    name: auth-service
  messages:
    encoding: ISO-8859-1
    
management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /api/docs
    enabled: true

aas:
  cache:
    size: 0
    ttl: 5m
  iam:
    base-uri: http://key-server:8080
    iat:
      dcr-uri: ${aas.iam.base-uri}/realms/gaia-x/clients-registrations/openid-connect
      redirect-uri: ${aas.oidc.issuer}/*
      secret: "{noop}iat"
    clients:
       oidc:
         id: aas-app-oidc
         secret: "{noop}secret"
         redirect-uri: ${aas.iam.base-uri}/realms/gaia-x/broker/ssi-oidc/endpoint
       siop:
         id: aas-app-siop
         secret: "{noop}secret2"
         redirect-uri: ${aas.iam.base-uri}/realms/gaia-x/broker/ssi-siop/endpoint
       gxfs:
         id: gxfs-hmi-demo
         secret: "{noop}hmi-secret"
         redirect-uri: http://127.0.0.1:3000
  jwk:
    length: 3072
    secret: 96ec048e-c640-4cfd-bc82-6571810a9d0f
  oidc:
    issuer: http://auth-server:8090
  siop:
    clock-skew: 5s 
    issuer: https://self-issued.me/v2
  scopes:
    openid:
      - sub
      - iss
      - auth_time
    profile:
      - name
      - given_name
      - family_name
      - middle_name
      - preferred_username
      - gender
      - birthdate
      - updated_at
    email:
      - email
      - email_verified
  token:
    ttl: 5m
  tsa:
    url: http://trustservice/api
    repo: aisbl
    group: example
    version: 1.0
    action: evaluation
    delay: 500 # in milliseconds
    duration: 5000 # in milliseconds
    request:
      count: 2
    statuses:
      GetLoginProofResult: ACCEPTED
      GetIatProofResult: ACCEPTED
    
logging:
  level:
    root: INFO
    tsclaims: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    eu.gaiax.difs.aas: DEBUG
